### ISSUE TITLE
Basler Camera feed into GUI

### ISSUE THREAD

**Issue by rcbullins** [DeepLabCut/DeepLabCut-live-GUI#6]
Hello,

I have a Basler USB camera I am wanting to add to the DLC live GUI. 

In order to get the DLC live GUI to open, I made the changes specified in issue #4. The Basler camera is compatible with OpenCV, but for an unknown reason I am not able to open the Basler camera in the GUI. I was able to open the Basler camera through python using the following script on the Basler Github: https://github.com/basler/pypylon/blob/master/samples/opencv.py 

However, I am not sure how to integrate this into the DLC Live GUI Camera opencv.py script. Do you have an idea on how to go about integrating the Basler opencv.py script into your opencv.py script of the DLC live GUI work flow?

Thank you!

**Comment by MMathisLab** [comment]
hi @rcbullins I have never used a Basler camera, so I am not sure ... I tagged @gkane26 maybe he has some ideas, but unfortunately I don't have a camera to test so I can't help much!

**Comment by gkane26** [comment]
hi @rcbullins -- so the link you provided that successfully reads images from your camera doesn't actually use OpenCV to access the camera. Instead, it uses the Basler's pypylon library to access the camera, and once it fetches the image data, it converts the image to a format that can be used by OpenCV. I think the best solution here is to write a new camera module specifically for Basler cameras using the pypylon library. 

I made a new minimal Basler camera module on the [basler branch](/DeepLabCut/DeepLabCut-live-GUI/tree/basler) using the examples from the pypylon library. Since we don't have any Basler cameras to test out, I can't troubleshoot and get this fully functional, but this will at least provide the starting structure for debugging! Please let me know if you have any further questions.

**Comment by antortjim** [comment]
Hi @gkane26, I also have a Basler USB3 camera and wisht to combine it with DLC. I recently started writing a minimal Python module to interface with my camera using pypylon while providing a frontend similar to raspivid
https://github.com/shaliulab/baslerpi/tree/master/src/baslerpi
Maybe we can integrate it here for other Basler users?
I have tried using aravis, the software you mention here https://github.com/DeepLabCut/DeepLabCut-live-GUI/blob/master/docs/camera_support.md to interface with Basler cameras. Even though I installed it successfully in my system (Ubuntu 20.04), I don't see it as a type of camera when I click Camera > Add camera > Init camera in dlcliveGUI. Maybe I am missing something?

Antonio

**Comment by antortjim** [comment]
I noticed the problem was I don't have the `gi` module installed. After installing it, I get another error regarding `Tcam`

```
import gi
gi.require_version("Tcam", "0.1")
# ValueError: Namespace Tcam not available
```

I confirm that commenting out the `require_version` and removing the `Tcam` import in `cameras/tiscamera_linux.py` allows me to see the option TisCAM in deeplabcutlive. But I don't seem to be able to configure further.
Maybe I can place my own module to interact with the camera instead?
And how can I fix this Tcam error? Is Tcam really needed?

**Comment by gkane26** [comment]
Hi @antortjim! Thanks for bringing up this issue. First, ignore the tiscamera things as that is a specific library for The Imaging Source cameras. If Aravis cameras are not showing up as an option, then there must be an issue with the installation of the aravis library (also, we may need to provide better instructions). Can you try importing the aravis module directly (outside of the GUI) to test: `from dlclivegui.camera.aravis import AravisCam`

Alternatively, you could try to use your Basler USB camera using the OpenCVCam module. Not a guarantee that this will work but its worth a shot!

Lastly, we would love to include a Basler specific module (using the pypylon library), but we don't have the bandwith nor a Basler camera to test it ourselves right now. If you'd like to contribute it, that would be awesome! You would have edit the module you linked above to fit in with the DLC-Live-GUI framework (basic instructions on the [camera support page](https://github.com/DeepLabCut/DeepLabCut-live-GUI/blob/master/docs/camera_support.md), and please use our existing camera modules as examples).

**Comment by antortjim** [comment]
Hi @gkane26  thanks for such a quick reply!

Indeed the import statement does not work. I have installed Aravis (v0.8) and I can see the live feed from the camera with arv-viewer, but I did not do any Pygobject linking or anything. I have no idea how Pygobject works, but I see it's used here in dlclivegui, so maybe I need to do something about it?

```
$ python
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dlclivegui.camera.aravis import AravisCam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luna.kuleuven.be/u0127714/anaconda3/envs/flybowl/lib/python3.7/site-packages/dlclivegui/camera/aravis.py", line 15, in <module>
    gi.require_version("Aravis", "0.6")
  File "/home/luna.kuleuven.be/u0127714/anaconda3/envs/flybowl/lib/python3.7/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Aravis not available
```
I can try integrating my module into DLC if I manage to find some time :)

Thank you!
Antonio

**Comment by MMathisLab** [comment]
Merged!
